# Desafio 5

Neste desafio, vamos praticar sobre redução de dimensionalidade com PCA e seleção de variáveis com RFE. Utilizaremos o _data set_ [Fifa 2019](https://www.kaggle.com/karangadiya/fifa19), contendo originalmente 89 variáveis de mais de 18 mil jogadores do _game_ FIFA 2019.

> Obs.: Por favor, não modifique o nome das funções de resposta.

## _Setup_ geral

In [1]:
from math import sqrt

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import scipy.stats as sct
import seaborn as sns
import statsmodels.api as sm
import statsmodels.stats as st
from sklearn.decomposition import PCA
from sklearn.feature_selection import RFE
from sklearn.model_selection import train_test_split
from yellowbrick.model_selection import RFECV
from sklearn.linear_model import LinearRegression
from loguru import logger

In [2]:
# Algumas configurações para o matplotlib.
#%matplotlib inline

from IPython.core.pylabtools import figsize


figsize(12, 8)

sns.set()

In [3]:
fifa = pd.read_csv("data/fifa.csv")

In [4]:
columns_to_drop = ["Unnamed: 0", "ID", "Name", "Photo", "Nationality", "Flag",
                   "Club", "Club Logo", "Value", "Wage", "Special", "Preferred Foot",
                   "International Reputation", "Weak Foot", "Skill Moves", "Work Rate",
                   "Body Type", "Real Face", "Position", "Jersey Number", "Joined",
                   "Loaned From", "Contract Valid Until", "Height", "Weight", "LS",
                   "ST", "RS", "LW", "LF", "CF", "RF", "RW", "LAM", "CAM", "RAM", "LM",
                   "LCM", "CM", "RCM", "RM", "LWB", "LDM", "CDM", "RDM", "RWB", "LB", "LCB",
                   "CB", "RCB", "RB", "Release Clause"
]

try:
    fifa.drop(columns_to_drop, axis=1, inplace=True)
except KeyError:
    logger.warning(f"Columns already dropped")

## Inicia sua análise a partir daqui

In [5]:
fifa.dropna(inplace=True)

## Questão 1

Qual fração da variância consegue ser explicada pelo primeiro componente principal de `fifa`? Responda como um único float (entre 0 e 1) arredondado para três casas decimais.

In [28]:
def q1():
    pca = PCA(n_components=1)
    projeto = pca.fit_transform(fifa)
    evr = pca.explained_variance_ratio_

    return round(evr[0],3)

q1()

0.565

## Questão 2

Quantos componentes principais precisamos para explicar 95% da variância total? Responda como un único escalar inteiro.

In [7]:
def q2():
    pca = PCA(n_components=0.95)
    projeto = pca.fit_transform(fifa)
    
    return projeto.shape[1]

q2()

15

## Questão 3

Qual são as coordenadas (primeiro e segundo componentes principais) do ponto `x` abaixo? O vetor abaixo já está centralizado. Cuidado para __não__ centralizar o vetor novamente (por exemplo, invocando `PCA.transform()` nele). Responda como uma tupla de float arredondados para três casas decimais.

In [30]:
x = [0.87747123,  -1.24990363,  -1.3191255, -36.7341814,
     -35.55091139, -37.29814417, -28.68671182, -30.90902583,
     -42.37100061, -32.17082438, -28.86315326, -22.71193348,
     -38.36945867, -20.61407566, -22.72696734, -25.50360703,
     2.16339005, -27.96657305, -33.46004736,  -5.08943224,
     -30.21994603,   3.68803348, -36.10997302, -30.86899058,
     -22.69827634, -37.95847789, -22.40090313, -30.54859849,
     -26.64827358, -19.28162344, -34.69783578, -34.6614351,
     48.38377664,  47.60840355,  45.76793876,  44.61110193,
     49.28911284
]

(186.556, -6.592)

In [35]:
vector_x = np.array(x)
type(vector_x)
vector_x

array([  0.87747123,  -1.24990363,  -1.3191255 , -36.7341814 ,
       -35.55091139, -37.29814417, -28.68671182, -30.90902583,
       -42.37100061, -32.17082438, -28.86315326, -22.71193348,
       -38.36945867, -20.61407566, -22.72696734, -25.50360703,
         2.16339005, -27.96657305, -33.46004736,  -5.08943224,
       -30.21994603,   3.68803348, -36.10997302, -30.86899058,
       -22.69827634, -37.95847789, -22.40090313, -30.54859849,
       -26.64827358, -19.28162344, -34.69783578, -34.6614351 ,
        48.38377664,  47.60840355,  45.76793876,  44.61110193,
        49.28911284])

In [47]:
principalComponents = pca.fit_transform(vector_x.reshape(-1, 1))

In [62]:
pca = PCA(n_components=1)
projeto = pca.fit_transform(vector_x.reshape(-1, 1))

In [68]:
pca = PCA(n_components=1)
vector_x = np.array(x)
type(vector_x)

pca.fit(vector_x.reshape(-1, 1))

PCA(copy=True, iterated_power='auto', n_components=1, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [81]:
rng = np.random.RandomState(1)
X = np.dot(rng.rand(2, 2), rng.randn(2, 200)).T
pca = PCA(n_components=1)
pca.fit(X)
X_pca = pca.transform(X)
print("original shape:   ", X.shape)
print("transformed shape:", X_pca.shape)

original shape:    (200, 2)
transformed shape: (200, 1)


In [85]:
X_pca

array([[ 6.76769235e-01],
       [-1.07121393e+00],
       [ 7.27912364e-01],
       [ 2.30964136e+00],
       [ 6.30052323e-01],
       [ 1.02448887e+00],
       [ 7.77183507e-01],
       [-1.39656414e+00],
       [-2.91049874e-01],
       [ 1.88864221e+00],
       [-7.11544293e-01],
       [ 6.38884130e-01],
       [ 5.48059617e-01],
       [-2.19312436e-01],
       [-3.87789490e-01],
       [ 7.15219956e-01],
       [-1.08373816e+00],
       [-2.99917403e-01],
       [-7.96849021e-01],
       [-8.12568346e-01],
       [-1.54018281e+00],
       [-2.52920476e-01],
       [ 6.26464454e-01],
       [-1.61007571e+00],
       [ 5.04240563e-01],
       [ 5.53935753e-01],
       [ 6.81911252e-01],
       [-2.00157228e-02],
       [ 1.13550833e-01],
       [ 2.92286085e-02],
       [-2.14393483e-01],
       [-1.03406124e+00],
       [ 3.88635004e-01],
       [ 9.96727811e-01],
       [ 1.39223653e+00],
       [ 4.57043694e-01],
       [ 6.81839901e-01],
       [-9.05233246e-01],
       [ 4.9

In [82]:
X_new = pca.inverse_transform(X_pca)

In [83]:
X_new

array([[-0.60566999, -0.22648439],
       [ 1.0452307 ,  0.34794757],
       [-0.65397264, -0.24329133],
       [-2.14785286, -0.76308793],
       [-0.56154772, -0.21113202],
       [-0.93407737, -0.34075396],
       [-0.70050728, -0.25948309],
       [ 1.35251105,  0.45486597],
       [ 0.30839673,  0.09156571],
       [-1.75023588, -0.62473684],
       [ 0.70553701,  0.22975093],
       [-0.56988901, -0.21403438],
       [-0.48410886, -0.18418712],
       [ 0.24064357,  0.06799096],
       [ 0.39976345,  0.12335682],
       [-0.64198517, -0.23912028],
       [ 1.05705933,  0.35206335],
       [ 0.31677176,  0.09447981],
       [ 0.78610394,  0.25778425],
       [ 0.80095021,  0.26295002],
       [ 1.48815318,  0.50206274],
       [ 0.27238503,  0.07903542],
       [-0.55815912, -0.20995296],
       [ 1.55416425,  0.52503133],
       [-0.44272351, -0.16978706],
       [-0.48965864, -0.18611817],
       [-0.61052642, -0.22817419],
       [ 0.05241574,  0.00249696],
       [-0.07373257,

In [77]:
pca = PCA(n_components=1)
vector_x = np.array(X_pca)
X_new = pca.inverse_transform(x)
X_new

AttributeError: 'PCA' object has no attribute 'components_'

In [70]:
print(pca.mean_)
print(pca.explained_variance_ratio_)
print(pca.components_)
print(pca.explained_variance_)

[-15.00811302]
[1.]
[[1.]]
[772.56058507]


In [9]:
def q3():
    return (0.5, 0.5)

## Questão 4

Realiza RFE com estimador de regressão linear para selecionar cinco variáveis, eliminando uma a uma. Quais são as variáveis selecionadas? Responda como uma lista de nomes de variáveis.

In [10]:
fifa_x = fifa.drop('Overall',1)
fifa_y =  fifa['Overall']

In [11]:
X_train, X_test, y_train, y_test = train_test_split(fifa_x,  fifa_y)

In [12]:
reg = LinearRegression()
reg.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [13]:
rfe = RFE(reg)

In [14]:
rfe.fit(X_train, y_train)

RFE(estimator=LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False),
  n_features_to_select=None, step=1, verbose=0)

In [15]:
resultado = pd.DataFrame({
    'colunas': X_train.columns,
    'bool':rfe.get_support(),
    'coeficientes': pd.Series(reg.coef_)
})

In [16]:
resultados_validos = resultado[resultado['bool'] == True]

In [17]:
cinco_resultados = resultados_validos.sort_values(by='coeficientes', ascending=False )[:5]

In [18]:
resposta = list(cinco_resultados['colunas'])

In [20]:
def q4():
    return resposta

q4()

['Potential', 'Age', 'Reactions', 'BallControl', 'GKDiving']